### ISSUE TITLE
No admin in a society

### ISSUE THREAD

**Issue by jysim3** [Ivan-Velickovic/HallHackathon#10]
There is no way to make someone an admin.

Steps to reproduce:
`
$ python3

>>> from util.events import createSingleEvent, createRecurrentEvent
>>> from util.users import createUser, getUserAttendance
>>> from util.participation import register
>>> from util.societies import createSociety, createSocStaff, findSocID, joinSoc
>>> from util.utilFunctions import checkEvent
>>> from datetime import datetime

>>> createUser("z1234567", "Thanos", "123456")
'Success'
>>> createSociety("z1234567", "Infinity")
'1A408'

>>> events.createSingleEvent('z1234567', 'eventID', 'eventName', '2020-01-01', 'true', 'location', findSocID("Infinity"), 'description', None)
'not an admin'
>>> events.createSingleEvent('z1234567', 'eventID', 'eventName', '2020-01-01', 'true', 'location', '1A408', 'description', None)
'not an admin'

>>> createSocStaff('z1234567', '1A408', 1)
'failed'
>>> createSocStaff('z1234567', findSocID("Infinity"), 1)
'failed'

>>> events.createSingleEvent('z1234567', 'eventID', 'eventName', '2020-01-01', 'true', 'location', '1A408', 'description', None)
'not an admin'
`

**Comment by StevenShen1999** [comment]
Implemented in `POST /api/soc/makeAdmin`. Requires a superadmin account's token to be accessed.
