### ISSUE TITLE
Backend support for given sign up information

### ISSUE THREAD

**Issue by Ivan-Velickovic** [Ivan-Velickovic/HallHackathon#9]
```
zID: string,
password: string,
comencmentYear: integer,
studentType: "domestic" || "international",
degreeType: "undergraduate" || "postgraduate",
isArcMember: boolean
```

This is the data I've got it on the frontend, from what I can see it won't all be used in the backend. Let me know if I should change the format.

**Comment by StevenShen1999** [comment]
Added additional parametres for /api/auth/register. Make sure to reinitialise database on pull.
